apiVersion: v1
kind: Service
metadata:
  name: juanvidal-mariadb
spec:
  ports:
  - port: 3306
  selector:
    app: juanvidal-mariadb
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pfw-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/sda1/pfw_pv"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pfw-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: juanvidal-mariadb
  labels:
    app: juanvidal-mariadb
spec:
  containers:
  - image: mariadb:10.0
    name: mariadb
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: banana
    ports:
    - containerPort: 3306
      name: mariadb
    volumeMounts:
    - mountPath: /docker-entrypoint-initdb.d
      name: init-db
  volumes:
    - name: init-db
      hostPath:
        path: /home/docker/PersonalizedFitWorkouts/database/initdb.d  # directory location on host
        type: Directory
    - name: pfw-pv-storage
      persistentVolumeClaim:
        claimName: pfw-pv-claim
