apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  ports:
  - port: 3306
  selector:
    app: mariadb
---
apiVersion: v1
kind: Pod
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  containers:
  - image: mariadb:10.0
    name: mariadb
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: banana
    ports:
    - containerPort: 3306
      name: mariadb
    volumeMounts:
    - mountPath: /docker-entrypoint-initdb.d
      name: init-db
  volumes:
    - name: init-db
      hostPath:
        path: /home/docker/PersonalizedFitWorkouts/database/initdb.d  # directory location on host
        type: Directory
