apiVersion: v1
kind: Service
metadata:
  name: juanvidal-pdfcreator
spec:
  ports:
  - port: 8090
  selector:
    app: juanvidal-pdfcreator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: juanvidal-pdfcreator
spec:
  selector:
    matchLabels:
      app: juanvidal-pdfcreator
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: juanvidal-pdfcreator
    spec:
      containers:
      - image: juanvidal-pdfcreator
        imagePullPolicy: IfNotPresent
        name: pdfcreator
        env:
        - name: DB_USERNAME
          value: pdfcreator
        - name: DB_PASSWORD
          value: pdfcreator-password
        - name: DB_HOST
          value: juanvidal-mariadb
        - name: DB_NAME
          value: test
        - name: DB_PORT
          value: "3306"
        ports:
        - containerPort: 8090
          name: pdfcreator
