# Default values for pfw.

db:
    service_name: "juanvidal-mariadb"
    port: 3306
    database_name: "pfwdb"
    host_paths:
        pv: "/mnt/sda1/pfw_pv"
        initdb: "/home/docker/PersonalizedFitWorkouts/database/initdb.d"
    credentials:
        root_password: "mariadb-root-password"
        rw_user: "pfwmain"
        rw_pass: "pfwmain-password"
        ro_user: "pdfcreator"
        ro_pass: "pdfcreator-password"

pdfcreator:
    image: "juanvidal-pdfcreator"
    service_name: "juanvidal-pdfcreator"
    port: 8090
    replicas: 2

pfw_main:
    image: "juanvidal-pfw-main"
    service_name: "juanvidal-pfw-main"
    port: 8080
    replicas: 2

ingress:
    hostname: "juanvidal.pfw.example.com"
