apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: juanvidal-pfw-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.pfw_main.service_name }}
          servicePort: {{ .Values.pfw_main.port }}
